### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by renanmt** [strayiker/vs-theme-darcula#1]
Hi, I'm just passing here to say thanks for the amazing theme. I found this in a comment section somewhere, I even lost the reference.
If by any chance you have this posted on some website, let me know so I can share with even more people.

Cheers!

**Comment by michaelkonecny** [comment]
Same here! Thank you so much. You saved my eyes!

**Comment by strayiker** [comment]
NP bros! )

**Comment by jfaquinojr** [comment]
You sir, are awesome!

**Comment by mitsukuri** [comment]
Thank you so much for your time working on this great scheme, which does not seem an easy undertaking, given the absurdly high number of customizable colors in VS! (yes, I really think MS has overengineered on this, to the point that creating a theme from scratch seems next to impossible).

**Comment by holsby** [comment]
Cheers!  has saved my eyes!  I've tried to merge it with the 'dark-bliss' theme from studiostyl.es and updated for VS2017 (now that the colour theme editor is available - as of v15.3) and it is hopefully attached to this comment.
[darcula-Bliss-vs-2017.zip](https://github.com/strayiker/vs-theme-darcula/files/1245265/darcula-Bliss-vs-2017.zip)

**Comment by chip-pragma** [comment]
**THANK YOU!**
