### ISSUE TITLE
VS2017

### ISSUE THREAD

**Issue by grobee** [strayiker/vs-theme-darcula#3]
Hi!

Thank you for this amazing theme, it is my favorite and love using it. I was actually able to import it into VS2017 Color themes and it works for the most part, but there are occasions when the theme does not line up. The problem is that some parts of the VS2017 product's UI have changed. Can we expect a VS2017 version of your theme?

Thanks in advance!

**Comment by strayiker** [comment]
I merged the [PR for VS2017 support](https://github.com/strayiker/vs-theme-darcula/pull/2), but i have no enough time for check it. But you can try it anyway.
