### ISSUE TITLE
Xaml Editor Error Color

### ISSUE THREAD

**Issue by Drewfyre** [strayiker/vs-theme-darcula#6]
Hey there,

first of all I really love the theme and am going to keep using it. Just one thing I wasnt able to fix by myself.
write a lot of C# and XAML.
The problem I have is the color of the little square you get on the scrollbar when there is a parsing error in your xaml code. For most of all editor this is a red square, however in the xaml one it is blue and really irritating for my eyes.
Now I tried making a screenshot of the square and using gimp figured out that it was just pure blue (rgb 0,0,255) so I tried to go to the color customizer, select your theme and used the search function to look for "0000FF". I turned all of those into the normal red , hit save & apply but still the little square is blue.
Do you have any idea which property I need to modify in order to change that color?

Oh also here have a screenshot so you know what I'm actuall talking about 

![grafik](https://user-images.githubusercontent.com/20600823/37509018-dc584672-28f5-11e8-8208-6b4865359e4c.png)

![grafik](https://user-images.githubusercontent.com/20600823/37509049-f6529d16-28f5-11e8-98a9-d552a3f0fdcd.png)

**Comment by strayiker** [comment]
Please, check this issue with new darcula-vs-2019.vstheme
