### ISSUE TITLE
VS 2019 Update

### ISSUE THREAD

**Issue by augustocb23** [strayiker/vs-theme-darcula#7]
First of all, thanks by this theme. It's great!

I recent updated my VS to 2019 version and the theme have just a small fixes needed. Please, update the theme to VS 2019.

The print above shows the new welcome page, with the default light theme mixed with the Darcula colors.

![image](https://user-images.githubusercontent.com/14170426/57696546-55651200-7627-11e9-9243-28d43de04e4c.png)

**Comment by ronnyek** [comment]
I managed to find keys to make the dialog at least dark background, but it doesnt feel at home with the rest of the theme... I'm terrible at that sort of thing.

That being said @strayiker is there any hope of updates for visual studio 2019? This is by far the best implementation of really any theme I've seen for visual studio. I even suggested adding it to official themes

**Comment by strayiker** [comment]
Hello! darcula-vs-2019.vstheme is now available, check it.
